### ISSUE TITLE
Chrome/Mac: dragging slider arrows shows (+) mouse tip

### ISSUE THREAD

**Issue by cwillems** [openHPI/video-player#12]
Currently, when dragging one of the slider arrows to change the video ratio in dual stream mode, the browser shows a (+) at the mouse pointer (like when copying files), as if i was about to drag the arrow image out of the browser window (e.g. to drop it on the desktop).

This applies at least to Chrome (latest) on Mac OS X (latest).

**Comment by jonathanherdt** [comment]
This happens because of a workaround for Windows: In video-player.html we added `ondragover` and `ondrag` events for the video streams so Windows would not display a blocked / not allowed sign anymore. As long as dragging happens, Windows apparently has to show some kind of symbol and the plus sign is better than a blocked sign. If we rework the resizer to not use dragging anymore, as outlined in #23, this problem will also disappear.

**Comment by soldag** [comment]
Fixed in 9b262a7.
