### ISSUE TITLE
Analytics Event for Volume Change / Mute

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/video-player#33]
Please also send an analytics events when the volume is changed or muted.

**Comment by sebastiankliem** [comment]
fixed by [#33_volume_change](https://github.com/openHPI/videoplayer/tree/%2333_volume_change) / https://github.com/openHPI/videoplayer/commit/7de572a2ee371954564a0f935572ded823fdb745.

Both volume change und muted state trigger the same event, as setting a volume when in a muted state also unmutes the player and this could not be captured otherwise.

**Comment by tobiasrohloff** [comment]
Sounds totally fine!
