### ISSUE TITLE
Config for videoPreload ignored

### ISSUE THREAD

**Issue by tobiasrohloff** [openHPI/video-player#49]
It seems like the config `"videoPreload": false` is ignored. Please look at the [OpenWHO](https://openwho.org) landing page for an example. Tested on latest Chrome, macOS.

**Comment by janrenz** [comment]
Version 1.2.2 is the rolled out version

**Comment by janrenz** [comment]
In safari it seems to work, maybe chrome ignores this setting or just preloads a "bit"

**Comment by soldag** [comment]
When `videoPreload` is set to `false`, the `preload` attribute of the video elements is set to `metadata` so that the duration of the video is retrieved. That's why the video is loaded a bit, which is the case in latest Chrome, macOS on my computer.
However, in my Safari the entire video is loaded on the openWHO landing page, although the `preload` attribute is set correctly. According to the HTML spec, `preload` is only a hint to the browser, which may be ignored in some instances. It seems like this is the case here.

**Comment by tobiasrohloff** [comment]
@soldag can this be closed if this is vendor-specific behavior?

**Comment by soldag** [comment]
👍
